### ISSUE TITLE
 mobx.extras.setReactionScheduler is not a function

### ISSUE THREAD

**Issue by mmintel** [philcockfield/storybook-host#10]
Hi there,

after installing it like documented in your README i am getting the following error:

```
TypeError: mobx.extras.setReactionScheduler is not a function
    at Object.defineProperty.value (webpack:///./~/mobx-react/index.js?:151:104)
    at __webpack_require__ (webpack:///./~/mobx-react/index.js?:30:30)
    at Object.defineProperty.value (webpack:///./~/mobx-react/index.js?:50:18)
    at eval (webpack:///./~/mobx-react/index.js?:53:10)
    at webpackUniversalModuleDefinition (webpack:///./~/mobx-react/index.js?:3:20)
    at eval (webpack:///./~/mobx-react/index.js?:10:3)
    at Object.<anonymous> (http://localhost:9001/static/preview.bundle.js:9648:2)
    at __webpack_require__ (http://localhost:9001/static/preview.bundle.js:554:30)
    at fn (http://localhost:9001/static/preview.bundle.js:85:20)
    at n (webpack:///./~/mobx-react-devtools/index.js?:1:87)
```

Do I miss some dependencies?

Cheers!

**Comment by philcockfield** [comment]
MobX removed
